#include <sdkddkver.h>

import "Windows.Foundation.idl";

namespace WinRTServer
{
	runtimeclass Server;

	[version(1.0), uuid(9a860baf-a1e9-44e1-9035-78fd22220046), exclusiveto(Server)]
	interface IServer : IInspectable
	{
		HRESULT Initialize();
		[eventadd] HRESULT Initialized([in] Windows.Foundation.TypedEventHandler<IInspectable*, IInspectable*>* handler, [out, retval] EventRegistrationToken* token);
		[eventremove] HRESULT Initialized([in] EventRegistrationToken token);
	};

	[version(1.0), uuid(f19bff5c-6e8f-4c1d-a5bb-e50591ca69c2), exclusiveto(Server)]
	interface IServerFactory : IInspectable
	{
	}

	[version(1.0), activatable(1.0), activatable(IServerFactory, 1.0)]
	runtimeclass Server
	{
		[default] interface IServer;
	}
}
